object Dependencies {
    const val composeBom = "androidx.compose:compose-bom:${Versions.composeBomVersion}"

    const val junitExtension = "androidx.test.ext:junit:${Versions.junitExtensionVersion}"
    const val junit = "junit:junit:${Versions.junitVersion}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtxVersion}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycleRuntimeKtxVersion}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.activityComposeVersion}"
    const val baristaCompose = "com.adevinta.android:barista-compose:${Versions.composeBarista}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hiltAndroidVersion}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hiltCompilerVersion}"
    const val timberLogging = "com.jakewharton.timber:timber:${Versions.timerLoggingVersion}"
    const val ktorClientCore = "io.ktor:ktor-client-core:${Versions.ktorVersion}"
    const val ktorClientContentNegotiation = "io.ktor:ktor-client-content-negotiation:${Versions.ktorVersion}"
    const val ktorSerializationKotlinJson = "io.ktor:ktor-serialization-kotlinx-json:${Versions.ktorVersion}"
    const val ktorClientAndroid = "io.ktor:ktor-client-android:${Versions.ktorVersion}"
    const val ktorClientLogging = "io.ktor:ktor-client-logging:${Versions.ktorVersion}"
    const val webView = "androidx.browser:browser:${Versions.webViewVersion}"
    const val securityCrypto = "androidx.security:security-crypto:${Versions.securityCryptoVersion}"
    const val splashScreen = "androidx.core:core-splashscreen:${Versions.splashScreenVersion}"
}