internal object Versions {
    const val composeBomVersion = "2023.08.00"
    const val composeBarista = "4.3.0"
    const val junitExtensionVersion = "1.1.5"
    const val junitVersion = "4.13.2"
    const val coreKtxVersion = "1.12.0"
    const val lifecycleRuntimeKtxVersion = "2.6.2"
    const val activityComposeVersion = "1.8.1"
    const val hiltAndroidVersion = "2.46"
    const val hiltCompilerVersion = "2.46"
    const val timerLoggingVersion = "5.0.1"
    const val ktorVersion = "2.3.0"
    const val webViewVersion = "1.7.0"
    const val securityCryptoVersion = "1.1.0-alpha06"
    const val splashScreenVersion = "1.0.1"
    const val dataStoreVersion = "1.0.0"
    const val protobufJavaLiteVersion = "3.24.4"
    const val protobufKotlinVersion = "3.24.4"
    const val coreNavigationVersion = "2.7.6"
    const val tracingVersion = "1.2.0"
    const val metricsPerformanceVersion = "1.0.0-beta01"
    const val lifecycleRuntimeComposeVersion = "2.7.0"
    const val collapsableToolbarItemVersion = "2.3.5"
    const val hiltNavigationComposeVersion= "1.0.0"
}